trigger:
- master

variables:
  buildConfiguration: 'Release'

stages:
- stage: Windows
  displayName: Build and create Nuget 
  jobs:
  - job: Build
    displayName: Build and Test
    pool:
      vmImage: 'windows-latest'

    steps:
  
      - task : UseDotNet@2
        displayName: Add .NET 5.0.x SDK
        inputs:
          packageType: 'sdk'
          version: '5.0.x'

      - task: DotNetCoreCLI@2
        displayName: Restore projects
        inputs:
          command: 'restore'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        displayName: Build projects
        inputs:
          command: 'build'
          arguments: '-c $(buildConfiguration) --no-restore'

      - task: DotNetCoreCLI@2
        displayName: Test projects
        inputs:
          command: 'test'
          arguments: '-c $(buildConfiguration) --no-build --no-restore --verbosity normal'

      - task: DotNetCoreCLI@2
        displayName: 'dotnet pack'
        inputs:
          command: pack
          packagesToPack: '**/*.csproj'
          includesymbols: true
          includesource: true

      # - task: DotNetCoreCLI@2
      #   displayName: 'dotnet push'
      #   inputs:
      #     command: push
      #     packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      #     publishVstsFeed: '9a0959b1-2e35-47b9-b9f6-0982dd44e0a9'
